[theme]
primaryColor="#3D5EAA"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"
layout="wide"

[server]
enableCORS = false
enableXsrfProtection = false
